/*
 * File: app/view/CBI.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CBI', {
    extend: 'Ext.form.Panel',
    alias: 'widget.cbi',

    config: {
        iconCls: 'insurance',
        title: 'CBI',
        height: '',
        ui: 'light',
        width: '100%',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'CBI',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 92,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 92,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 91,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: 300,
                id: 'PremiumTAB',
                items: [
                    {
                        xtype: 'container',
                        title: '.',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'container',
                                height: 80,
                                top: 10,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Badge:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%',
                                        options: [
                                            {
                                                value: 'A',
                                                text: 'A'
                                            },
                                            {
                                                value: 'M',
                                                text: 'M'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        left: '',
                                        right: '1%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Premium: $',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 80,
                                id: 'bpli',
                                maxHeight: 80,
                                minHeight: 80,
                                top: 105,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Loan Contract No:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '',
                                        right: '1%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Insure Term (months)',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 79,
                                top: 200,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: ' Total Payable Premium:',
                                        left: '2%',
                                        top: 10,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: '0.0 ',
                                        left: '30%',
                                        top: 10,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'Standard Cover:',
                                        left: '55%',
                                        top: 10,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: '0.0 ',
                                        left: '75%',
                                        top: 10,
                                        width: ''
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 25,
                                        html: '',
                                        right: '.3%',
                                        top: 10,
                                        width: '11%',
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            },
            {
                xtype: 'tabpanel',
                height: 370,
                id: 'optionTAB',
                maxHeight: 370,
                minHeight: 370,
                width: '100%',
                items: [
                    {
                        xtype: 'container',
                        title: 'Option',
                        cls: [
                            'tabBG'
                        ],
                        height: 310,
                        maxHeight: 310,
                        minHeight: 310,
                        items: [
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 15,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: '1',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '80%',
                                name: 'cbiOptions',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 110,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: '2',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '80%',
                                name: 'cbiOptions'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '',
                                right: '.5%',
                                top: 15,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: '3',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '80%',
                                name: 'cbiOptions'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                right: '.5%',
                                top: 110,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: '4',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '80%',
                                name: 'cbiOptions'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 205,
                                width: '98.5%',
                                inputCls: 'textBlack',
                                label: 'None',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '90.5%',
                                name: 'cbiOptions'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            },
            {
                xtype: 'tabpanel',
                height: 370,
                id: 'coverTerm',
                maxHeight: 370,
                minHeight: 370,
                width: '100%',
                items: [
                    {
                        xtype: 'container',
                        title: 'Cover Term',
                        cls: [
                            'tabBG'
                        ],
                        height: 310,
                        maxHeight: 310,
                        minHeight: 310,
                        items: [
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 15,
                                width: '98.5%',
                                inputCls: 'textBlack',
                                label: '3 years',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '90.5%',
                                name: 'coverterm',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 110,
                                width: '98.5%',
                                inputCls: 'textBlack',
                                label: '4 years',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '90.5%',
                                name: 'coverterm'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'textBlack'
                                ],
                                left: '1%',
                                top: 205,
                                width: '98.5%',
                                inputCls: 'textBalck',
                                label: '5 years',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '90.5%',
                                name: 'coverterm'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});