/*
 * File: app/view/Customer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Customer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.customer',

    config: {
        iconCls: 'customer',
        title: 'Customer',
        ui: 'light',
        width: '',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Customer',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 93,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 87,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 88,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: 530,
                id: 'genderTAB',
                left: '',
                top: '',
                width: '',
                items: [
                    {
                        xtype: 'container',
                        title: '.',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '1%',
                                top: 10,
                                width: '35%',
                                inputCls: 'textBlack',
                                label: 'Title:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%',
                                options: [
                                    {
                                        value: 'Mr',
                                        text: 'Mr.'
                                    },
                                    {
                                        value: 'Ms',
                                        text: 'Ms.'
                                    },
                                    {
                                        value: 'Mrs',
                                        text: 'Mrs.'
                                    },
                                    {
                                        value: 'D',
                                        text: 'Dr.'
                                    },
                                    {
                                        value: 'P',
                                        text: 'Professor.'
                                    }
                                ]
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '40.5%',
                                top: 10,
                                width: '27%',
                                inputCls: 'textBlack',
                                label: 'Male',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '60%',
                                name: 'gendergroup',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '',
                                right: '1%',
                                top: 10,
                                width: '27%',
                                inputCls: 'textBlack',
                                label: 'Female',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '60%',
                                name: 'gendergroup'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '1%',
                                top: 100,
                                width: '98%',
                                inputCls: 'textBlack',
                                label: 'First Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '35%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '1%',
                                top: 190,
                                width: '98%',
                                inputCls: 'textBlack',
                                label: 'Middle  Name:',
                                labelCls: 'normalLabelText',
                                labelWidth: '35%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '1%',
                                top: 280,
                                width: '98%',
                                inputCls: 'textBlack',
                                label: 'Last  Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '35%'
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '',
                                right: '1%',
                                top: 370,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: 'Business #:',
                                labelCls: 'normalLabelText',
                                labelWidth: '35%'
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                left: '1%',
                                top: 370,
                                width: '47%',
                                inputCls: 'textBlack',
                                label: 'Mobile #:',
                                labelCls: 'normalLabelText',
                                labelWidth: '35%'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});