/*
 * File: app/view/Insurance.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Insurance', {
    extend: 'Ext.form.Panel',
    alias: 'widget.insurance',

    config: {
        iconCls: 'insurance',
        title: 'Insurance',
        top: '',
        ui: 'light',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'CCI',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 94,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 88,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 86,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 89,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 45,
                width: '100%',
                items: [
                    {
                        xtype: 'selectfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        left: '.5%',
                        width: '45%',
                        inputCls: 'textBlack',
                        label: 'Badge:',
                        labelCls: 'normalLabelText',
                        name: 'badgepremium',
                        options: [
                            {
                                value: 'A',
                                text: 'A'
                            },
                            {
                                value: 'M',
                                text: 'M'
                            }
                        ]
                    },
                    {
                        xtype: 'numberfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        left: '55%',
                        width: '38%',
                        inputCls: 'textBlack',
                        label: 'Premium: $',
                        labelCls: 'normalLabelText',
                        labelWidth: '35%',
                        name: 'badgepremium'
                    },
                    {
                        xtype: 'image',
                        docked: 'left',
                        height: 25,
                        html: '',
                        maxWidth: '11%',
                        minWidth: '11%',
                        right: '-4%',
                        top: 10,
                        width: '11%',
                        src: 'images/statusfalse.png'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 60
            },
            {
                xtype: 'container',
                height: 45,
                width: '100%',
                items: [
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        left: '.5%',
                        width: '45%',
                        inputCls: 'textBlack',
                        label: 'Private',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '70%',
                        name: 'privatebusiness',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        left: '55%',
                        right: '',
                        width: '38%',
                        inputCls: 'textBlack',
                        label: 'Business',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'privatebusiness'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 60
            },
            {
                xtype: 'container',
                height: 660,
                width: '100%',
                items: [
                    {
                        xtype: 'tabpanel',
                        height: 630,
                        id: 'InsuranceProductTAB',
                        left: '.5%',
                        width: '45%',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Insurance Product',
                                cls: [
                                    'tabBG'
                                ],
                                items: [
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'textBlack',
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                left: '.5%',
                                                width: '45%',
                                                inputCls: '',
                                                label: 'Joint Cover',
                                                labelAlign: 'right',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'textBlack',
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                right: '.5%',
                                                width: '45%',
                                                label: 'Balloon Cover',
                                                labelAlign: 'right',
                                                labelWidth: '70%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 100
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                width: '70%',
                                                label: 'Life:',
                                                labelAlign: 'right',
                                                labelCls: '',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '$ 0.00 ',
                                                right: '5%',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                width: '70%',
                                                label: 'Trauma:',
                                                labelAlign: 'right',
                                                labelCls: 'tranBG',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '$ 0.00 ',
                                                right: '5%',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                width: '70%',
                                                label: 'Disability',
                                                labelAlign: 'right',
                                                labelCls: '',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '$ 0.00 ',
                                                right: '5%',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                width: '70%',
                                                label: 'Involuntary Unemployment:',
                                                labelAlign: 'right',
                                                labelCls: 'tranBG',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '$ 0.00 ',
                                                right: '5%',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'left',
                                                width: '70%',
                                                label: 'None:',
                                                labelAlign: 'right',
                                                labelCls: 'tranBG',
                                                labelWidth: '70%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'left',
                        height: 650,
                        left: '46%',
                        width: '10%',
                        items: [
                            {
                                xtype: 'container',
                                height: 170,
                                width: 150
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 150,
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: 30,
                                        width: '50%',
                                        text: 'i'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                left: 0,
                                top: 250,
                                width: 150,
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'RS: 67',
                                        left: 3,
                                        styleHtmlContent: true
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'RC: 2767',
                                        left: '',
                                        styleHtmlContent: true,
                                        top: 50
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        height: 630,
                        id: 'COPLinsuranceTAB',
                        right: '.5%',
                        width: '45%',
                        items: [
                            {
                                xtype: 'container',
                                title: 'COPL Insurance',
                                cls: [
                                    'tabBG'
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: 'Amount Financed:',
                                                styleHtmlContent: true,
                                                width: ''
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'staticText'
                                                ],
                                                docked: 'left',
                                                html: '2,356.00',
                                                styleHtmlContent: true,
                                                width: ''
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'staticText'
                                                ],
                                                docked: 'right',
                                                html: 'Excl. PPI',
                                                right: '10%',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: 'Balloon Residual:',
                                                styleHtmlContent: true,
                                                width: ''
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '0.00 ',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        width: '100%'
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: 'Payment Frequency:',
                                                left: 2,
                                                styleHtmlContent: true,
                                                width: ''
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '0.00 ',
                                                left: 240,
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabled: true,
                                        disabledCls: ' ',
                                        left: '5%',
                                        top: 300,
                                        width: '90%',
                                        inputCls: 'textBlack',
                                        label: 'Insure Term (months):',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: 'Finance Term:',
                                                styleHtmlContent: true,
                                                width: ''
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'cciStaticText'
                                                ],
                                                docked: 'left',
                                                html: '',
                                                styleHtmlContent: true,
                                                width: ''
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 20
            },
            {
                xtype: 'container',
                height: 200,
                width: '100%',
                items: [
                    {
                        xtype: 'tabpanel',
                        height: 200,
                        id: 'CCIPeriodTAB',
                        items: [
                            {
                                xtype: 'container',
                                title: 'CCI Period of Cover',
                                cls: [
                                    'tabBG'
                                ],
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabled: true,
                                        disabledCls: ' ',
                                        docked: 'left',
                                        height: 45,
                                        left: '.5%',
                                        top: 30,
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'From:',
                                        labelCls: 'normalLabelText',
                                        placeHolder: 'mm/dd/yyyy'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabled: true,
                                        disabledCls: ' ',
                                        docked: 'left',
                                        height: 45,
                                        left: '',
                                        right: '.5%',
                                        top: 30,
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'To:',
                                        labelCls: 'normalLabelText',
                                        placeHolder: 'mm/dd/yyyy'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 60
            },
            {
                xtype: 'tabpanel',
                height: 650,
                id: 'COPLdetails',
                width: '100%',
                items: [
                    {
                        xtype: 'container',
                        title: 'COPL Insurance',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'spacer',
                                height: 20
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        right: '.5%',
                                        width: '99%',
                                        inputCls: 'textBlack',
                                        label: 'Vehicle Rego Number:',
                                        labelCls: 'normalLabelText'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 20
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'cciStaticText'
                                        ],
                                        docked: 'left',
                                        html: 'Credit Provider:',
                                        styleHtmlContent: true,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'cciStaticText'
                                        ],
                                        docked: 'left',
                                        html: 'ANZ Banking Group ltd.',
                                        styleHtmlContent: true,
                                        width: ''
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 20
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'cciStaticText'
                                        ],
                                        docked: 'left',
                                        html: 'Loan Commencement Date:',
                                        styleHtmlContent: true,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'cciStaticText'
                                        ],
                                        docked: 'left',
                                        html: '26/06/2012',
                                        styleHtmlContent: true,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'cciStaticText'
                                        ],
                                        docked: 'left',
                                        html: '* must be same as insurance cover date ',
                                        styleHtmlContent: true,
                                        width: ''
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 50
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        right: '.5%',
                                        width: '99%',
                                        inputCls: 'textBlack',
                                        label: 'Loan Contract Number:',
                                        labelCls: 'normalLabelText'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 40
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'Type of Contract:',
                                        styleHtmlContent: true
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 20
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '.5%',
                                        top: '',
                                        width: '30%',
                                        inputCls: 'textBlack',
                                        label: 'Regulated',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '0.5%',
                                        top: 100,
                                        width: '30%',
                                        inputCls: 'textBlack',
                                        label: 'Hire Purchase',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '35%',
                                        width: '30%',
                                        inputCls: 'textBlack',
                                        label: 'Lease',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '35%',
                                        top: 100,
                                        width: '30%',
                                        inputCls: 'textBlack',
                                        label: 'Chattal Mortgage',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        left: '69.5%',
                                        right: '.',
                                        width: '30%',
                                        inputCls: 'textBlack',
                                        label: 'Cash Deal',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'container',
                height: 830,
                width: '100%',
                items: [
                    {
                        xtype: 'tabpanel',
                        height: 820,
                        id: 'FirstInsudedTab',
                        left: '.01%',
                        width: '45%',
                        items: [
                            {
                                xtype: 'container',
                                title: '1st Insured',
                                cls: [
                                    'tabBG'
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        height: '',
                                        left: '',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'right',
                                                right: '',
                                                width: '60%',
                                                label: 'Client Age OK',
                                                labelWidth: '70%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 20
                                    },
                                    {
                                        xtype: 'container',
                                        height: '',
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Status:',
                                                labelWidth: '45%',
                                                options: [
                                                    {
                                                        value: 'FT',
                                                        text: 'Full Time'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Employer:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Occupation:',
                                                labelWidth: '45%',
                                                options: [
                                                    {
                                                        value: 'PE',
                                                        text: 'Professional/Exective'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Hours per week:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Employ period (months):',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                height: 170,
                                                label: 'Medical Condition to declare:',
                                                labelWidth: '65%',
                                                options: [
                                                    {
                                                        value: 'Y',
                                                        text: 'Y'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'textareafield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'If YES enter details:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        height: 820,
                        id: 'SecondInsudedTab',
                        right: '.01%',
                        width: '45%',
                        items: [
                            {
                                xtype: 'container',
                                title: '2nd Insured',
                                cls: [
                                    'tabBG'
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        height: '',
                                        left: '.5%',
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'cbInput'
                                                ],
                                                docked: 'right',
                                                width: '60%',
                                                label: 'Client Age OK',
                                                labelWidth: '70%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Status:',
                                                labelWidth: '45%',
                                                options: [
                                                    {
                                                        value: 'FT',
                                                        text: 'Full Time'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Employer:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Occupation:',
                                                labelWidth: '45%',
                                                options: [
                                                    {
                                                        value: 'PE',
                                                        text: 'Professional/Exective'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Hours per week:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Employ period (months):',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'Medical Condition to declare:',
                                                labelWidth: '65%',
                                                options: [
                                                    {
                                                        value: 'Y',
                                                        text: 'Y'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        left: '.5%',
                                        width: '99%',
                                        items: [
                                            {
                                                xtype: 'textareafield',
                                                cls: [
                                                    'textBlack',
                                                    'normalRoundCorner'
                                                ],
                                                label: 'If YES enter details:',
                                                labelWidth: '45%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'spacer',
                                        height: 95
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});