/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.LoginForm',

    config: {
        styleHtmlContent: true,
        ui: 'dark',
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        scrollable: false,
        cls: [
            'contentBGSquare'
        ],
        items: [
            {
                xtype: 'container',
                border: 2,
                centered: true,
                cls: [
                    'loginBG'
                ],
                height: 550,
                html: '<body background="images/bg.png"></body>',
                padding: '',
                top: '',
                ui: 'dark',
                width: 735,
                items: [
                    {
                        xtype: 'container',
                        height: '',
                        left: '22%',
                        right: 5,
                        top: '30%',
                        width: 470,
                        items: [
                            {
                                xtype: 'label',
                                cls: [
                                    'productName'
                                ],
                                draggable: true,
                                height: '',
                                html: 'FINANCE AND INSURANCE APPLICATION',
                                id: '',
                                left: '',
                                padding: '',
                                right: '',
                                styleHtmlContent: true,
                                top: '55%',
                                ui: '',
                                width: 500
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        left: 225,
                        right: '',
                        top: 118,
                        items: [
                            {
                                xtype: 'label',
                                cls: [
                                    'productVersion'
                                ],
                                docked: 'left',
                                height: 31,
                                html: '<b><font color="#FD803D">Version  1.00.00 build 120923</font></b>',
                                styleHtmlContent: true,
                                width: 350
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: 'none',
                        cls: [
                            'textInput'
                        ],
                        height: '',
                        left: 130,
                        right: '',
                        top: 170,
                        width: 500,
                        items: [
                            {
                                xtype: 'textfield',
                                border: '',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                id: 'userID',
                                itemId: 'userID',
                                padding: '',
                                style: '',
                                width: '100%',
                                label: 'User Name:',
                                labelCls: 'normalLabelText ',
                                labelWidth: '35%',
                                value: 'mcopl001'
                            },
                            {
                                xtype: 'passwordfield',
                                border: '',
                                bottom: '',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                padding: 5,
                                width: '100%',
                                label: 'Password:',
                                labelCls: 'normalLabelText ',
                                labelWidth: '35%',
                                value: 'flying098'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        left: 390,
                        right: '7%',
                        top: 400,
                        items: [
                            {
                                xtype: 'button',
                                action: 'LoginAction',
                                cls: '',
                                docked: 'left',
                                height: 56,
                                id: 'loginButton',
                                ui: 'confirm',
                                width: 234,
                                text: 'Login'
                            }
                        ]
                    },
                    {
                        xtype: 'image',
                        height: 86,
                        left: 280,
                        top: 20,
                        width: 86,
                        src: 'images/logo_.png'
                    },
                    {
                        xtype: 'image',
                        height: 63,
                        id: 'logoText',
                        left: 380,
                        top: 30,
                        width: 149,
                        src: 'images/logoText.png'
                    },
                    {
                        xtype: 'image',
                        bottom: 40,
                        height: 200,
                        left: 15,
                        top: 150,
                        width: 50,
                        src: 'images/sideLock.png'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onFormpanelShow',
                event: 'show'
            }
        ]
    },

    onFormpanelShow: function(component, options) {
        Ext.getCmp('userID').focus('', 10);
    }

});