/*
 * File: app/view/MVI.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MVI', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mvi',

    config: {
        iconCls: 'insurance',
        title: 'MVI',
        ui: 'light',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'MVI',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 99,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 94,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 94,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 95,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: 550,
                id: 'mciTAB',
                left: '10%',
                width: '80%',
                items: [
                    {
                        xtype: 'container',
                        title: 'Comprehensive Insurer',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                left: '',
                                right: '10%',
                                top: '',
                                width: '80%',
                                inputCls: 'textBlack',
                                label: 'Insurer Name:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'AAMI',
                                        text: 'AAMI'
                                    },
                                    {
                                        value: 'ABC',
                                        text: 'ABC Insurance'
                                    },
                                    {
                                        value: 'ALLIANZ',
                                        text: 'ALLIANZ AUSTRALIA Insurance Limited'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                height: 100
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 46,
                                left: '',
                                right: '10%',
                                top: '',
                                width: '80%',
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Insurance Policy Number: ',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'spacer',
                                height: 100
                            },
                            {
                                xtype: 'datepickerfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                left: '',
                                right: '10%',
                                top: '',
                                width: '80%',
                                inputCls: 'textBlack',
                                label: 'Renewal Date:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%',
                                placeHolder: 'mm/dd/yyyy'
                            },
                            {
                                xtype: 'spacer',
                                height: 100
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 46,
                                id: 'prem',
                                left: '',
                                right: '10%',
                                top: '',
                                width: '48%',
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Premium:     $',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%',
                                value: 0
                            },
                            {
                                xtype: 'spacer',
                                height: 100
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 46,
                                id: 'comm',
                                left: '',
                                right: '10%',
                                top: '',
                                width: '48%',
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Commission: $',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%',
                                value: 0
                            },
                            {
                                xtype: 'label',
                                cls: [
                                    'staticText'
                                ],
                                docked: 'left',
                                html: '*excluding GST',
                                left: '12%',
                                right: '',
                                top: 430,
                                width: ''
                            }
                        ]
                    }
                ]
            }
        ]
    }

});