/*
 * File: app/view/Summary.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Summary', {
    extend: 'Ext.form.Panel',
    alias: 'widget.summary',

    config: {
        iconCls: 'summary',
        title: 'Summary',
        ui: 'light',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                style: '',
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Summary',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 104,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 89,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 95,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png',
                        iconAlign: 'center',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: 600,
                id: 'FinanceTAB',
                items: [
                    {
                        xtype: 'container',
                        title: 'Finance',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'container',
                                height: '',
                                left: 10,
                                top: 10,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'mandatoryRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        id: 'vehiclePrice',
                                        itemId: 'vehiclePrice',
                                        left: '.05%',
                                        minHeight: 45,
                                        style: 'inputField',
                                        width: '40%',
                                        inputCls: 'textBlackRight',
                                        label: 'Vehicle Price:',
                                        labelCls: 'mandatoryLabelText',
                                        value: 0.00
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        html: 'Payments: Monthly: ',
                                        left: '45%',
                                        right: 320,
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        html: '  0.00',
                                        left: '64%',
                                        right: 280,
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 30,
                                        html: 'Equivalent Weekly:',
                                        left: '75%',
                                        right: 50,
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 32,
                                        html: ' 0.00',
                                        left: '94%',
                                        right: 15,
                                        top: 20,
                                        width: 30
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                left: 10,
                                top: 100,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        html: 'Loan Period: ',
                                        left: '2%',
                                        padding: 5,
                                        right: '',
                                        top: 15
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        html: ' 0.00',
                                        left: '15%',
                                        maxWidth: '',
                                        minWidth: '',
                                        right: '',
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: 'From:',
                                        left: '25%',
                                        right: '',
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: '06/06/2012',
                                        left: '31%',
                                        right: '',
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: 'To:',
                                        left: '45%',
                                        right: '',
                                        top: 20,
                                        width: 179
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: '06/06/2012',
                                        left: '49%',
                                        right: '',
                                        top: 20,
                                        width: ''
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'onlyRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        right: '13%',
                                        top: '',
                                        width: '20%',
                                        inputCls: '',
                                        label: 'Display All',
                                        labelAlign: 'right',
                                        labelCls: '',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: 45,
                                        maxWidth: '',
                                        minWidth: '',
                                        right: '1%',
                                        top: '',
                                        width: 100,
                                        text: 'P'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                id: 'gridTitle',
                                top: 200,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'Monthly',
                                        left: 180,
                                        maxWidth: '',
                                        minWidth: '',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'Weekly',
                                        left: 450,
                                        maxWidth: '',
                                        minWidth: '',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'Total Premium',
                                        left: 700,
                                        maxWidth: '',
                                        minWidth: '',
                                        width: 150
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                id: 'gridCCI',
                                top: 250,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'CCI',
                                        left: 30,
                                        maxWidth: '18%',
                                        minWidth: '18%',
                                        padding: 5,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 200,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 475,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 750,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 25,
                                        left: '85%',
                                        maxWidth: '11%',
                                        minWidth: '11%',
                                        right: '',
                                        width: '11%',
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                id: 'gridEPI',
                                top: 300,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'EPI',
                                        left: 30,
                                        maxWidth: '18%',
                                        minWidth: '18%',
                                        padding: 5,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 200,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 475,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 750,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 25,
                                        left: '85%',
                                        maxWidth: '11%',
                                        minWidth: '11%',
                                        right: '',
                                        width: '11%',
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                id: 'gridCBI',
                                top: 350,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'CBI',
                                        left: 30,
                                        maxWidth: '18%',
                                        minWidth: '18%',
                                        padding: 5,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 200,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 475,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 750,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 25,
                                        left: '85%',
                                        maxWidth: '11%',
                                        minWidth: '11%',
                                        right: '',
                                        width: '11%',
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                id: 'gridWTY',
                                top: 400,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: 'WTY',
                                        left: 30,
                                        maxWidth: '18%',
                                        minWidth: '18%',
                                        padding: 5,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 200,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 475,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        html: ' 0.0',
                                        left: 750,
                                        maxWidth: '20%',
                                        minWidth: '20%',
                                        width: ''
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 25,
                                        left: '85%',
                                        maxWidth: '11%',
                                        minWidth: '11%',
                                        right: 50,
                                        width: '11%',
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                left: 10,
                                top: 450,
                                width: '98%',
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '',
                                        width: '60%',
                                        inputCls: 'textBlack',
                                        label: 'Forward Date Documents to:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%',
                                        name: '',
                                        value: {
                                            year: 2012,
                                            month: 6,
                                            day: 5
                                        },
                                        placeHolder: 'mm/dd/yyyy',
                                        dateFormat: 'd/m/Y',
                                        picker: {
                                            height: '30%',
                                            maxHeight: '30%',
                                            minHeight: '30%',
                                            doneButton: {
                                                height: 45,
                                                maxHeight: 45,
                                                minHeight: 45
                                            },
                                            cancelButton: {
                                                height: 45,
                                                maxHeight: 45,
                                                minHeight: 45
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 30,
                                        html: 'Maximum 5 days',
                                        left: '5%',
                                        padding: 5,
                                        top: 15,
                                        width: ''
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: '',
                                        left: '60%',
                                        width: 100,
                                        text: 'Clear'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});