/*
 * File: app/view/WTY.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WTY', {
    extend: 'Ext.form.Panel',
    alias: 'widget.wty',

    config: {
        iconCls: 'insurance',
        title: 'WTY',
        ui: 'light',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'WTY',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        action: 'CancelAction',
                        docked: 'right',
                        width: 92,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 92,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        action: 'PrintAction',
                        docked: 'right',
                        width: 88,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 85,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'container',
                height: 320,
                items: [
                    {
                        xtype: 'tabpanel',
                        height: 320,
                        items: [
                            {
                                xtype: 'container',
                                title: '.',
                                cls: [
                                    'tabBG'
                                ],
                                height: '',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: 'TP Warranty:',
                                        left: '2%',
                                        top: 35,
                                        width: '15%'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: 40,
                                        left: '18%',
                                        top: 20,
                                        width: 100,
                                        text: '...'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '.5%',
                                        top: 120,
                                        width: '32%',
                                        inputCls: 'textBlack',
                                        label: 'Product Type:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '45%',
                                        options: [
                                            {
                                                value: 'null',
                                                text: 'None'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '34%',
                                        top: 120,
                                        width: '32%',
                                        inputCls: 'textBlack',
                                        label: 'Badge:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '40%',
                                        options: [
                                            {
                                                value: 'A',
                                                text: 'A'
                                            },
                                            {
                                                value: 'M',
                                                text: 'M'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '',
                                        right: '.5%',
                                        top: 120,
                                        width: '32%',
                                        inputCls: 'textBlack',
                                        label: 'Premium: $',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '45%'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: 'Total Payable Premium:',
                                        left: '65%',
                                        top: 220,
                                        width: ''
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: '  0.0',
                                        left: '90%',
                                        top: 220,
                                        width: ''
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'container',
                height: 520,
                width: '99%',
                items: [
                    {
                        xtype: 'tabpanel',
                        height: 520,
                        id: 'WheelTyreTAB',
                        left: '.5%',
                        width: '35%',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Tyre and Wheel',
                                cls: [
                                    'tabBG'
                                ],
                                height: '',
                                items: [
                                    {
                                        xtype: 'container',
                                        height: 30,
                                        width: '100%',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 30,
                                                right: '1%',
                                                top: 15,
                                                width: '30%',
                                                src: 'images/statusfalse.png'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        top: 100,
                                        items: [
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 11
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                cls: [
                                                    'normalRoundCorner'
                                                ],
                                                docked: 'left',
                                                height: 45,
                                                width: '75%',
                                                inputCls: 'textBlack',
                                                label: 'Tyre and Wheel',
                                                labelCls: 'normalLabelText',
                                                labelWidth: '70%'
                                            },
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 1
                                            },
                                            {
                                                xtype: 'button',
                                                docked: 'left',
                                                height: 40,
                                                padding: 5,
                                                width: '10%',
                                                text: 'i'
                                            },
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 5
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'staticText'
                                                ],
                                                docked: 'left',
                                                height: 40,
                                                html: 'RS: 67',
                                                width: '13%'
                                            },
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 2
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'staticText'
                                                ],
                                                docked: 'left',
                                                height: 40,
                                                html: 'Rc:',
                                                width: '12%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 45,
                                        top: 200,
                                        items: [
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 11
                                            },
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'normalRoundCorner'
                                                ],
                                                docked: 'left',
                                                height: 45,
                                                width: '90%',
                                                inputCls: 'textBlack',
                                                label: 'Insure Term (months):',
                                                labelCls: 'normalLabelText',
                                                labelWidth: '60%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 35,
                                        top: 300,
                                        items: [
                                            {
                                                xtype: 'spacer',
                                                docked: 'left',
                                                height: 21,
                                                width: 11
                                            },
                                            {
                                                xtype: 'numberfield',
                                                cls: [
                                                    'normalRoundCorner'
                                                ],
                                                docked: 'left',
                                                height: 45,
                                                width: '90%',
                                                inputCls: 'textBlack',
                                                label: 'Premium:',
                                                labelCls: 'normalLabelText',
                                                labelWidth: '60%'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        height: 520,
                        id: 'VehicleGroupTAB',
                        left: '37%',
                        width: '26%',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Vehicle Group',
                                cls: [
                                    'tabBG'
                                ],
                                height: '',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 100,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: 'Group One',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'vehiclegroup',
                                        checked: true
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 200,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: 'Group Two',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'vehiclegroup'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        height: 520,
                        id: 'DealerPlanTAB',
                        right: '.5%',
                        width: '35%',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Dealer Warranty Plan',
                                cls: [
                                    'tabBG'
                                ],
                                height: '',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 10,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: '12 months',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'warrantyplangroup',
                                        checked: true
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 100,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: '24 months',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'warrantyplangroup'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 190,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: '36 months',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'warrantyplangroup'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 280,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: '48 months',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'warrantyplangroup'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        left: '7%',
                                        top: 370,
                                        width: '85%',
                                        inputCls: 'textBlack',
                                        label: '60 months',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'warrantyplangroup'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'tabpanel',
                height: 940,
                id: 'AssetWarrantyTAB',
                items: [
                    {
                        xtype: 'container',
                        title: 'Asset Warranty Information',
                        cls: [
                            'tabBG'
                        ],
                        items: [
                            {
                                xtype: 'container',
                                height: 80,
                                top: 20,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        left: '.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Vehicle purchase date by client:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 24,
                                        maxWidth: '1%',
                                        minWidth: '1%'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        right: '.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Vehicle Use:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        options: [
                                            {
                                                value: 'null',
                                                text: 'Select'
                                            },
                                            {
                                                value: 'P',
                                                text: 'Private'
                                            },
                                            {
                                                value: 'C',
                                                text: 'Commercial'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 120,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'spacer',
                                        left: '',
                                        maxWidth: '10%',
                                        minWidth: '5%'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '44.5%',
                                        inputCls: 'textBlack',
                                        label: 'Warranty policy date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 220,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        left: '',
                                        right: '1%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty start date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '44.5%',
                                        inputCls: 'textBlack',
                                        label: 'Odometer:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 320,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'spacer',
                                        left: '1%',
                                        maxWidth: '10%',
                                        minWidth: '5%'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'First Registration start date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 420,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '44.5%',
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty length:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        html: 'months',
                                        left: '46%',
                                        padding: 3,
                                        top: 10,
                                        width: '10%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 520,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '44.5%',
                                        inputCls: 'textBlack',
                                        label: 'Length of statutory warranty:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 50,
                                        html: 'days',
                                        left: '46%',
                                        padding: 3,
                                        top: 10,
                                        width: '4%'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: '',
                                        maxHeight: 180,
                                        minHeight: 150,
                                        right: '1%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Vehicle modification:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '45%%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 700,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty expiry:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'staticText'
                                        ],
                                        docked: 'left',
                                        height: 50,
                                        html: 'KM\'s',
                                        left: '46.5%',
                                        padding: 3,
                                        top: 10,
                                        width: '6%'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        right: '1%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Dealer Service Waiver:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '65%',
                                        options: [
                                            {
                                                value: 'Y',
                                                text: 'Yes'
                                            },
                                            {
                                                value: 'N',
                                                text: 'No'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: '',
                                top: 800,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        left: '1.5%',
                                        width: '45%',
                                        inputCls: 'textBlack',
                                        label: 'Finance Company:  (if financed)',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});