/*
 * File: app/model/Application.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Application', {
    extend: 'Ext.data.Model',
    alias: 'model.Application',

    uses: [
        'MyApp.model.ApplicationStatusCode',
        'MyApp.model.CBIPremium',
        'MyApp.model.EPIPremium',
        'MyApp.model.EPIPremium',
        'MyApp.model.LTPPremium',
        'MyApp.model.LTPPremium',
        'MyApp.model.EWPremium',
        'MyApp.model.EWPremium',
        'MyApp.model.ApplicationFinanceCompany',
        'MyApp.model.AgentSalePerson',
        'MyApp.model.CCIPremium',
        'MyApp.model.ApplicationFinanceCompany',
        'MyApp.model.Fee',
        'MyApp.model.Finance',
        'MyApp.model.CustomerCorporate',
        'MyApp.model.CustomerIndividual',
        'MyApp.model.CustomerIndividual',
        'MyApp.model.CCIPremium',
        'MyApp.model.CCIPremium',
        'MyApp.model.CCIPremium',
        'MyApp.model.MVPremium',
        'MyApp.model.MEPIPremium',
        'MyApp.model.DealData',
        'MyApp.model.CBIPremium',
        'MyApp.model.MEPIPremium',
        'MyApp.model.OtherInsurance',
        'MyApp.model.VIPPremium',
        'MyApp.model.VIPPremium'
    ],

    config: {
        fields: [
            {
                name: 'agentID',
                type: 'string'
            },
            {
                name: 'fsgID',
                type: 'string'
            },
            {
                name: 'applicationID',
                type: 'string'
            },
            {
                name: 'applicationIndicator',
                defaultValue: 'Q',
                type: 'string'
            },
            {
                name: 'departmentID',
                type: 'string'
            },
            {
                name: 'policyNumber',
                type: 'string'
            },
            {
                name: 'version',
                type: 'int'
            },
            {
                name: 'businessManagerID',
                type: 'string'
            },
            {
                name: 'cciDiscountAmount',
                type: 'int'
            },
            {
                name: 'financeProductID',
                type: 'string'
            },
            {
                name: 'cciPremium',
                type: 'auto'
            },
            {
                name: 'loanContractNumber',
                type: 'string'
            },
            {
                name: 'loanStartDate',
                type: 'date'
            },
            {
                name: 'creationDate',
                type: 'date'
            },
            {
                name: 'externalApplicationNumber',
                type: 'string'
            },
            {
                name: 'versionNumber',
                type: 'int'
            },
            {
                name: 'insuranceOnlyIndicator',
                defaultValue: 'F',
                type: 'string'
            },
            {
                name: 'epiDiscountAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'mepiDiscountAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'cbiDiscountAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'ewDiscountAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'commentText',
                type: 'string'
            },
            {
                name: 'conversionComment',
                type: 'string'
            },
            {
                name: 'cciPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'cbiPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'epiPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'mepiPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'wtyPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'wtyrPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'vipPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'tnwPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'ltpPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'cbiUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'cciUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'epiUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'mepiUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'wtyUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'vipUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'tnwUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'ltpUnderwrittenIndicator',
                defaultValue: 'U',
                type: 'string'
            },
            {
                name: 'approvalNumber',
                defaultValue: '',
                type: 'string'
            },
            {
                name: 'approvalRejectionIndicator',
                defaultValue: 'N',
                type: 'string'
            },
            {
                name: 'fastPrintIndicator',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'loanInNameOf',
                defaultValue: '',
                type: 'string'
            },
            {
                name: 'rateSetID',
                type: 'int'
            },
            {
                name: 'applicationIDFrom',
                type: 'string'
            },
            {
                name: 'archiveIndicator',
                type: 'string'
            },
            {
                name: 'compositeLiteIndicator',
                type: 'boolean'
            },
            {
                name: 'createdByWS',
                type: 'boolean'
            },
            {
                name: 'referenceNumber',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'tpRetailPrice',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'tpCommissionAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'totalCommissionAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'insCommissionAmount',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'defaultBMStateCode',
                type: 'string'
            },
            {
                name: 'cash',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'creditCard',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'cheque',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'forPurpose',
                defaultValue: '',
                type: 'string'
            },
            {
                name: 'customerProfileType',
                type: 'string'
            },
            {
                name: 'saleType',
                defaultValue: '',
                type: 'string'
            },
            {
                name: 'locumID',
                type: 'string'
            },
            {
                name: 'marginRate',
                defaultValue: 0,
                type: 'int'
            },
            {
                name: 'menuSellingProfile',
                type: 'auto'
            }
        ],
        hasOne: [
            {
                name: 'applicationStatusCode',
                model: 'MyApp.model.ApplicationStatusCode'
            },
            {
                name: 'cbiPremium',
                model: 'MyApp.model.CBIPremium'
            },
            {
                name: 'epiPremium',
                model: 'MyApp.model.EPIPremium'
            },
            {
                name: 'extraEPIPremiumTAS',
                model: 'MyApp.model.EPIPremium'
            },
            {
                name: 'extraLTPPremiumTAS',
                model: 'MyApp.model.LTPPremium'
            },
            {
                name: 'ltpPremium',
                model: 'MyApp.model.LTPPremium'
            },
            {
                name: 'ewPremium',
                model: 'MyApp.model.EWPremium'
            },
            {
                name: 'tnwPremium',
                model: 'MyApp.model.EWPremium'
            },
            {
                name: 'applicationFinanceCompany',
                model: 'MyApp.model.ApplicationFinanceCompany'
            },
            {
                name: 'salePerson',
                model: 'MyApp.model.AgentSalePerson'
            },
            {
                name: 'disabilityCCIPremium',
                model: 'MyApp.model.CCIPremium'
            },
            {
                name: 'applicationPremiumFinanceCompany',
                model: 'MyApp.model.ApplicationFinanceCompany'
            },
            {
                name: 'fee',
                model: 'MyApp.model.Fee'
            },
            {
                name: 'finance',
                model: 'MyApp.model.Finance'
            },
            {
                name: 'customerCorporate',
                model: 'MyApp.model.CustomerCorporate'
            },
            {
                name: 'customerIndividualOne',
                model: 'MyApp.model.CustomerIndividual'
            },
            {
                name: 'customerIndividualTwo',
                model: 'MyApp.model.CustomerIndividual'
            },
            {
                name: 'involUnEmploymentCCIPremium',
                model: 'MyApp.model.CCIPremium'
            },
            {
                name: 'lifeCCIPremium',
                model: 'MyApp.model.CCIPremium'
            },
            {
                name: 'traumaCCIPremium',
                model: 'MyApp.model.CCIPremium'
            },
            {
                name: 'mvPremium',
                model: 'MyApp.model.MVPremium'
            },
            {
                name: 'mepiPremium',
                model: 'MyApp.model.MEPIPremium'
            },
            {
                name: 'dealData',
                model: 'MyApp.model.DealData'
            },
            {
                name: 'extraCBIPremiumTAS',
                model: 'MyApp.model.CBIPremium'
            },
            {
                name: 'extraMEPIPremiumTAS',
                model: 'MyApp.model.MEPIPremium'
            },
            {
                name: 'otherInsurance',
                model: 'MyApp.model.OtherInsurance'
            },
            {
                name: 'vipPremium',
                model: 'MyApp.model.VIPPremium'
            },
            {
                name: 'extraVIPPremiumTAS',
                model: 'MyApp.model.VIPPremium'
            }
        ]
    }
});